### ISSUE TITLE
To specific of a test for pry gem

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/using-bundler#56]
Requires `gem "pry", :group => "development"`

**Comment by maxwellbenton** [comment]
Hi @aviflombaum and @sgharms,

I've editted the `spec/bundle_spec.rb` so that this test will pass if a student choose the block or hash syntax when including `pry` in the development group. As long as a student writes one of the following the test will pass (spaces and new lines are ignored on the block solution):

```
gem "pry", :group => "development"
gem "pry", group: "development"
gem "pry", group: :development
gem "pry", :group => :development

group :development do
  gem "pry"
end
```
